// This file is auto-generated by scripts/generate-convex-api.mjs
// Do not edit this file directly.
/* eslint-disable */
/* tslint:disable */

import type * as counterApi from "../api/counter_api";
import type * as tableApi from "../api/table_api";

/**
 * A type helper to build the API from modules, preserving the original function definitions.
 */
type ApiFromModules<Modules extends Record<string, any>> = {
  [ModuleName in keyof Modules]: Modules[ModuleName];
};

declare const fullApi: ApiFromModules<{
  counter: typeof counterApi;
  table: typeof tableApi;
}>;

export declare const api: typeof fullApi;
