// This file is auto-generated by scripts/generate-convex-api.mjs
// Do not edit this file directly.
/* eslint-disable */
/* tslint:disable */

export const api = {
  columns: {
    createColumn: "columns:createColumn",
    deleteColumn: "columns:deleteColumn",
    getAllColumnsWithTasks: "columns:getAllColumnsWithTasks",
  },
  tables: {
    getAdminTableData: "tables:getAdminTableData",
  },
  tasks: {
    createTask: "tasks:createTask",
    deleteTask: "tasks:deleteTask",
    moveTask: "tasks:moveTask",
    updateTask: "tasks:updateTask",
  },
};
