// This file is auto-generated by scripts/generate-convex-api.mjs
// Do not edit this file directly.
/* eslint-disable */
/* tslint:disable */

export const api = {
  counter: {
    createCounter: "counter:createCounter",
    getCounter: "counter:getCounter",
    incrementCounter: "counter:incrementCounter",
  },
  table: {
    getAdminTableData: "table:getAdminTableData",
  },
};
