// This file is auto-generated by scripts/generate-convex-api.mjs
// Do not edit this file directly.
/* eslint-disable */
/* tslint:disable */

import type * as columns from "../columns";
import type * as tables from "../tables";
import type * as tasks from "../tasks";

/**
 * A type helper to build the API from modules, preserving the original function definitions.
 */
type ApiFromModules<Modules extends Record<string, any>> = {
  [ModuleName in keyof Modules]: Modules[ModuleName];
};

declare const fullApi: ApiFromModules<{
  columns: typeof columns;
  tables: typeof tables;
  tasks: typeof tasks;
}>;

export declare const api: typeof fullApi;
