// This file is auto-generated by scripts/generate-convex-api.mjs
// Do not edit this file directly.
/* tslint:disable */

export const api = {
  counters: {
    createCounter: "counters:createCounter",
    getCounter: "counters:getCounter",
    incrementCounter: "counters:incrementCounter",
  },
  tables: {
    getAdminTableData: "tables:getAdminTableData",
  },
  tickets: {
    createTicket: "tickets:createTicket",
    getAllTickets: "tickets:getAllTickets",
  },
};
