// This file is auto-generated by scripts/generate-convex-api.mjs
// Do not edit this file directly.
/* tslint:disable */

import type * as counters from "../counters";
import type * as tables from "../tables";
import type * as tickets from "../tickets";

/**
 * A type helper to build the API from modules, preserving the original function definitions.
 */
type ApiFromModules<Modules extends Record<string, unknown>> = {
  [ModuleName in keyof Modules]: Modules[ModuleName];
};

declare const fullApi: ApiFromModules<{
  counters: typeof counters;
  tables: typeof tables;
  tickets: typeof tickets;
}>;

export declare const api: typeof fullApi;
